### ISSUE TITLE
Added a reply function that provides some different responses to non-commands

### ISSUE THREAD

**Issue by josephbooth** [esthercrawford/EstherBot#12]
Hi Esther.
I am not sure how to share my code with you for a small function I made for the bot I'm working on.

https://github.com/josephbooth/JBot/blob/master/script.js

There is a getReply function in the script.js file that might be useful for your bot.

Thank you for sharing your project.

**Comment by kazekagekorosu** [comment]
looks great! I'll have to try this on my estherbot!

**Comment by kazekagekorosu** [comment]
This is a really cool function, working really well on my estherbot thanks @josephbooth

**Comment by josephbooth** [comment]
you are very welcome @kazekagekorosu
