### ISSUE TITLE
deploying on heroku,build failed.

### ISSUE THREAD

**Issue by bharathgs** [esthercrawford/EstherBot#38]
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 6.9.1...
       Using default npm version: 3.10.8
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Installing node modules (package.json)
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror https://github.com/skhavari/smooch-bot.git /app/.npm/_git-remotes/git-https-github-com-skhavari-smooch-bot-git-5b388294: Cloning into bare repository '/app/.npm/_git-remotes/git-https-github-com-skhavari-smooch-bot-git-5b388294'...
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror https://github.com/skhavari/smooch-bot.git /app/.npm/_git-remotes/git-https-github-com-skhavari-smooch-bot-git-5b388294: remote: Invalid username or password.
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror https://github.com/skhavari/smooch-bot.git /app/.npm/_git-remotes/git-https-github-com-skhavari-smooch-bot-git-5b388294: fatal: Authentication failed for 'https://github.com/skhavari/smooch-bot.git/'
       npm ERR! Linux 3.13.0-105-generic
       npm ERR! argv "/tmp/build_f3953bab5d20fc596a36606e1bf02249/esthercrawford-EstherBot-0772fde/.heroku/node/bin/node" "/tmp/build_f3953bab5d20fc596a36606e1bf02249/esthercrawford-EstherBot-0772fde/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_f3953bab5d20fc596a36606e1bf02249/esthercrawford-EstherBot-0772fde/.npmrc"
       npm ERR! node v6.9.1
       npm ERR! npm  v3.10.8
       npm ERR! code 128
       
       npm ERR! Command failed: git clone --template=/app/.npm/_git-remotes/_templates --mirror https://github.com/skhavari/smooch-bot.git /app/.npm/_git-remotes/git-https-github-com-skhavari-smooch-bot-git-5b388294
       npm ERR! Cloning into bare repository '/app/.npm/_git-remotes/git-https-github-com-skhavari-smooch-bot-git-5b388294'...
       npm ERR! remote: Invalid username or password.
       npm ERR! fatal: Authentication failed for 'https://github.com/skhavari/smooch-bot.git/'
       npm ERR!
       npm ERR!
       npm ERR! If you need help, you may report this error at:
       npm ERR!     <https://github.com/npm/npm/issues>
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_f3953bab5d20fc596a36606e1bf02249/esthercrawford-EstherBot-0772fde/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push faileds

**Comment by RigleyC** [comment]
This problem went fixed, look #34

**Comment by bharathgs** [comment]
I did try. but that did not  work.

**Comment by saleemazad-dev** [comment]
Hi I have the same problem...

**Comment by saleemazad-dev** [comment]
bharathgs, have you solved this problem?

**Comment by saleemazad-dev** [comment]
Hi, if this problem is  persisting, please look at the Heroku URL path.  In the readme, if you use the link, it uses https://heroku.com/deploy?template=https://github.com/esthercrawford/estherbot.  Make sure you go to https://heroku.com/deploy?template=https://github.com/[your forked repository in github]

**Comment by bharathgs** [comment]
I've tried everything, yet it does not work.

**Comment by anushkmittal** [comment]
Still facing same issue!

**Comment by anushkmittal** [comment]
@esthercrawford does it still work?
